# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            TrueRandom
tagline:          'Abstrações perdidas no espaço'
description:      'Apenas ideias desconexas e frases postas pra fora que eventualmente formam textos.'
url:              http://www.inf.ufpr.br
baseurl:          /vsbc14/truerandom/

author:
  name:           'Vytor Calixto'
  url:            https://twitter.com/vytorcalixto

paginate:         5

gems: [jekyll-paginate]
